# Generated by Django 5.2 on 2025-05-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=100)),
                ('last_name', models.CharField(default=' ', max_length=100)),
                ('user_image', models.FileField(blank=True, null=True, upload_to='./profile_pic/')),
                ('creattedAt', models.DateTimeField(auto_now_add=True)),
                ('user_otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='api.userotp')),
            ],
        ),
    ]
