# Generated by Django 5.2 on 2025-05-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creattedAt',
            new_name='createdAt',
        ),
    ]
