# Generated by Django 5.2 on 2025-05-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unseen_messages',
        ),
    ]
