# Generated by Django 5.2 on 2025-05-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_last_message_remove_user_unseen_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otpID',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, to='api.otpuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
