# Generated by Django 5.2 on 2025-05-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_otpid_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otpID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.otpuser'),
        ),
    ]
