# Generated by Django 5.2 on 2025-05-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_otpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otpID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.otpuser'),
        ),
    ]
