# Generated by Django 5.2 on 2025-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_otpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='whatsappBackend/profile_pic/'),
        ),
    ]
